SELECT con_id, dbid, name 
FROM V$CONTAINERS 
WHERE CON_ID = 1;

SHOW CON_NAME;

SELECT NAME FROM V$PDBS;

CREATE USER C##COMMONUSER IDENTIFIED BY "commonuser" CONTAINER=ALL;
GRANT CONNECT TO C##COMMONUSER CONTAINER=ALL;
GRANT CREATE TABLE TO C##COMMONUSER CONTAINER=CURRENT;

SHOW USER;

CONN C##COMMONUSER/commonuser;

SHOW USER;
SHOW CON_NAME;

CREATE TABLE T1(A NUMBER);

ALTER SESSION SET CONTAINER=ORCLPDB;

SHOW CON_NAME;

SELECT OPEN_MODE FROM V$DATABASE;
SELECT STATUS FROM V$INSTANCE;

ALTER PLUGGABLE DATABASE ORCLPDB OPEN;

CREATE USER vinicios IDENTIFIED BY "teste123" CONTAINER=CURRENT;
GRANT CONNECT TO vinicios CONTAINER=CURRENT;

ALTER SESSION SET CONTAINER=CDB$ROOT;